export default function Head() {
  return (
    <>
      <title>Free Next.js Template for Startup and SaaS</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon.ico" />
      <link
          href="https://unpkg.com/flowbite@1.4.7/dist/flowbite.css"
          rel="stylesheet"
        />
    </>
  );
}
